# Generated by Django 2.1.3 on 2018-11-06 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181105_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_Posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 12, 28, 33, 964909, tzinfo=utc)),
        ),
    ]
