# Generated by Django 2.1.3 on 2018-11-06 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181106_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_Posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 12, 36, 24, 47781, tzinfo=utc)),
        ),
    ]
